
simulatorDesign.pdf: simulatorDesign.tex simulatorDesign.bib global/*.tex global/figures/*.pdf detailed/*.tex detailed/figures/*.pdf appendix/*.tex appendix/figures/*.pdf cati/*.tex cati/figures/*.pdf
	pdflatex simulatorDesign
	bibtex simulatorDesign
	pdflatex simulatorDesign
	pdflatex simulatorDesign
